CREATE DATABASE IF NOT EXISTS mochi DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE mochi;

CREATE TABLE IF NOT EXISTS users (
    id          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email       VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    created_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pets (
    id              BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id         BIGINT UNSIGNED NOT NULL UNIQUE,
    name            VARCHAR(64) NOT NULL DEFAULT 'Mochi',
    personality_json JSON NOT NULL,
    created_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    CONSTRAINT fk_pets_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS chat_history (
    id          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    pet_id      BIGINT UNSIGNED NOT NULL,
    role        ENUM('user', 'assistant') NOT NULL,
    content     TEXT NOT NULL,
    created_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    INDEX idx_chat_pet_time (pet_id, created_at),
    CONSTRAINT fk_chat_pet FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS memories (
    id          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    pet_id      BIGINT UNSIGNED NOT NULL,
    type        ENUM('long', 'event', 'relation') NOT NULL DEFAULT 'long',
    content     VARCHAR(1024) NOT NULL,
    importance  FLOAT NOT NULL DEFAULT 0.5,
    created_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    INDEX idx_mem_pet_time (pet_id, created_at),
    FULLTEXT INDEX ft_mem_content (content),
    CONSTRAINT fk_mem_pet FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS life_states (
    pet_id              BIGINT UNSIGNED PRIMARY KEY,
    mood                TINYINT UNSIGNED NOT NULL DEFAULT 70,
    love                TINYINT UNSIGNED NOT NULL DEFAULT 60,
    hungry              TINYINT UNSIGNED NOT NULL DEFAULT 30,
    energy              TINYINT UNSIGNED NOT NULL DEFAULT 80,
    last_interaction    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    CONSTRAINT fk_life_pet FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
